name:                recursive-zipper
version:             0.0.0.0
github:              "ChrisPenner/recursive-zipper"
license:             BSD3
author:              "Chris Penner"
maintainer:          "example@example.com"
copyright:           "2021 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Zippers over recursive data structures.
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/recursive-zipper#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- mtl
- containers
- free
- lens
- comonad
- transformers

library:
  source-dirs: src
